### ISSUE TITLE
Wrong merges in presence of not-in-sync submodules

### ISSUE THREAD

**Issue by ydirson** [felipec/git-reintegrate#12]
git-reintegrates commits all changes when merging, and this possibly includes spurious submodule changes.

Cases where this happens includes:
* switch to integration branch from another branch which has different submodule commits
* merging branches which do introduce submodule changes

**Comment by felipec** [comment]
Can you write an example script that generates this error?

**Comment by ydirson** [comment]
Will do. 

If I understand correcty, it happens on when you have first a merge that gets solved by 
autocontinue, and then a submodule update. I guess autocontinue uses something like "add -u" 
which takes the submodule change by mistake. 

----- Mail original -----

**Comment by felipec** [comment]
I'm not familiar with submodules. You would have to write a script to reproduce the issue.

**Comment by ydirson** [comment]
Finally took the time to write this test, see https://github.com/felipec/git-reintegrate/pull/15

**Comment by felipec** [comment]
All right, now that I was able to reproduce I saw an easy improvement that fixes it.
